// Generated by https://quicktype.io

export interface ResultCliente {
    ok:      boolean;
    msg:     string;
    cliente: Cliente[];
    token:   null;
}

export interface Cliente {
    _id:      string;
    dni:      string;
    nombre:   string;
    tipo:     string;
    estado:   boolean;
    password: string;
    mes:      number;
    ano:      number;
}
