// Generated by https://quicktype.io

export interface ResultUser{
    ok:      boolean;
    msg?: string;
    usuario: Usuario[];
}

export interface Usuario {
    _id:      string;
    nombre:   string;
    usuario:  string;
    rol:      string;
    estado:   boolean;
    password: string;
}